# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hCiWGsx5F5PomyFz1QgYHE-cAG1j4B30
"""

import os
class Aspirador:
  def __init__(self, bateria, posicao, sala):
    self.bateria = bateria
    self.posicao = posicao # [x, y]
    self.sala = sala

  def lerSensor(self):
    raio = 1
    for k in range(3):
      raio = raio + k
      print("Raio: "+str(raio))
      for i in range(self.posicao[0] - raio, raio*2):  # pelo eixo x
        for j in range(self.posicao[1] - raio, raio*2):  # pelo eixo x
          # i e j armazenam a posição na sala
          if i < 0 or i > 2:
            continue
          if j < 0 or j > 3:
            continue

          print(j)
          print(i)
          if self.sala[i][j] == 1:
            self.limpar(i,j)
            return

  def limpar(self, i, j):
    print("Limpou")
    self.posicao = [i,j]  # Alterar posição do robô
    self.sala[i][j] = 0  # Limpar

sala = [
    [0,0,1],
    [0,0,0],
    [1,0,0]
    ]
posicao = [0,0]
bateria = 20
meu_robo = Aspirador(bateria, posicao, sala)
meu_robo.lerSensor()